import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@uploadthing/react/styles.css";
import LoadingProvider from "./_context/LoadingProvider";
import { Toaster as ShadcnTaster } from "@/components/ui/toaster";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/theme-provider";
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Auth Tutorial",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <html lang="en">
                <body className={poppins.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <LoadingProvider>
                            {children}
                            <ShadcnTaster />
                            <Toaster />
                        </LoadingProvider>
                    </ThemeProvider>
                </body>
            </html>
        </SessionProvider>
    );
}
